name: CD

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: CD-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: npm
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: 'steps.cache.outputs.cache-hit == false'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Success pipeline execution notification
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *${{ github.triggering_actor }}* successfully <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|deployed> *${{ github.repository }}* from *${{ github.ref_name }}* to *${{ env.ENVIRONMENT }}*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Failure pipeline execution notification
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":x: *${{ github.triggering_actor }}* failed to <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|deploy> *${{ github.repository }}* from *${{ github.ref_name }}* to *${{ env.ENVIRONMENT }}*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
